apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env.vars }}
  {{ $key }}: {{ $value }}
  {{- end }}
