apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.appPort }}
        readinessProbe:
          httpGet:
              path: /health
              port: {{ .Values.service.appPort }}
          initialDelaySeconds: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
              path: /health
              port: {{ .Values.service.appPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}-configmap
